import {mkdir,readFile,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const root=resolve(import.meta.dirname,'..'),site='https://suvarnatantu.com',blogRoot=resolve(root,'blog'),manifestFile=resolve(blogRoot,'.ghost-generated.json');
const categories=[['metallic-yarn','Metallic Yarn','Material, construction and performance insight for metallic yarn.','Guides & Insights'],['zari-yarn','Zari Yarn','Guidance on zari yarn selection, sheen and textile use.','Guides & Insights'],['technical-knowledge','Technical Knowledge','Clear explanations of yarn terms, specifications and process details.','Knowledge'],['applications','Applications','Learn how yarn choices translate into fabric and product outcomes.','& Use Cases'],['manufacturing','Manufacturing','Production knowledge from material preparation to final winding.','Process'],['export-sourcing','Export & Sourcing','Practical notes for dependable B2B sourcing and export supply.','& Sourcing'],['industry-insights','Industry Insights','Perspectives on textile markets, craft and emerging applications.','Insights']];
const categoryBySlug=new Map(categories.map(category=>[category[0],category]));
const normalizeCategory=value=>String(value||'').trim().toLowerCase().replace(/&/g,' and ').replace(/[\s_]+/g,'-').replace(/[^a-z0-9-]/g,'').replace(/-+/g,'-').replace(/^-|-$/g,'');
const categoryAliases=new Map([['metallic-yarn','metallic-yarn'],['zari-yarn','zari-yarn'],['technical-knowledge','technical-knowledge'],['applications','applications'],['manufacturing','manufacturing'],['export-sourcing','export-sourcing'],['export-and-sourcing','export-sourcing'],['industry-insights','industry-insights']]);
const canonicalCategory=post=>{for(const candidate of [post.primary_tag,...(post.tags||[])]){const slug=categoryAliases.get(normalizeCategory(candidate?.slug||candidate?.name));if(slug)return categoryBySlug.get(slug)}return null};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); const tag=post=>{const category=canonicalCategory(post);return category?{name:category[1],slug:category[0]}:post.primary_tag||post.tags?.[0]||{name:'Knowledge Centre',slug:'technical-knowledge'}}; const desc=p=>p.custom_excerpt||p.excerpt||''; const img=p=>p.feature_image||'/assets/images/metallic-zari-spools.webp'; const fmt=d=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric'}).format(new Date(d));
const json=o=>`<script type="application/ld+json">${JSON.stringify(o)}</script>`;
const normalizeArticleHtml=html=>String(html||'').replace(/<h1(\s[^>]*)?>([\s\S]*?)<\/h1\s*>/gi,(_,attributes='',content)=>`<h2${attributes}>${content}</h2>`);
function page({title,description,path,body,type='website',image,ogTitle,ogDescription,ld=''}){const url=site+path,og=image&&/^http/.test(image)?image:image?site+image:site+'/assets/images/metallic-zari-spools.webp';return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${url}"><link rel="icon" type="image/jpeg" href="/assets/images/suvarnatantu-logo.jpg"><link rel="stylesheet" href="/assets/css/styles.css?v=20260827-13"><link rel="stylesheet" href="/assets/css/knowledge-centre.css"><meta property="og:type" content="${type}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url}"><meta property="og:site_name" content="Suvarnatantu"><meta property="og:image" content="${og}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${og}">${ld}</head><body class="knowledge-centre"><div id="site-header-mount"></div><main>${body}</main><footer><div class="wrap"><span>© 2026 Suvarnatantu · by Vastranand Pvt. Ltd.</span><span>Yarn &amp; Metallic Zari Manufacturing · India</span></div></footer><script src="/assets/js/site-shell.js?v=20260829-1" defer></script><script src="/assets/js/site-shell-links.js" defer></script></body></html>`}
const card=p=>`<article class="kc-card"><a class="kc-card__image" href="/blog/${esc(p.slug)}/"><img src="${esc(img(p))}" alt="${esc(p.feature_image_alt||p.title)}" width="800" height="500" loading="lazy"></a><div class="kc-card__body"><a class="kc-tag" href="/blog/category/${esc(tag(p).slug)}/">${esc(tag(p).name)}</a><h3><a href="/blog/${esc(p.slug)}/">${esc(p.title)}</a></h3><p>${esc(desc(p))}</p><div class="kc-meta">${fmt(p.published_at)} · ${p.reading_time||4} min read</div></div></article>`;
async function data(){if(process.argv.includes('--demo'))return JSON.parse(await readFile(resolve(root,'scripts/ghost-content.sample.json'),'utf8'));const url=process.env.GHOST_CONTENT_API_URL?.replace(/\/$/,''),key=process.env.GHOST_CONTENT_API_KEY;if(!url||!key)throw Error('Set GHOST_CONTENT_API_URL and GHOST_CONTENT_API_KEY, or run npm run build:blog:demo.');const r=await fetch(`${url}/ghost/api/content/posts/?key=${encodeURIComponent(key)}&include=tags,authors&limit=all&fields=title,slug,custom_excerpt,excerpt,feature_image,feature_image_alt,published_at,updated_at,reading_time,html,meta_title,meta_description,og_title,og_description,og_image`);if(!r.ok)throw Error(`Ghost Content API returned ${r.status}.`);return r.json()}
async function emit(dir,html){const file=resolve(root,dir,'index.html');await mkdir(resolve(file,'..'),{recursive:true});await writeFile(file,html)}
// Generator-owned manifest: blog/.ghost-generated.json => {"version":1,"articles":["ghost-post-slug"]}.
// Only slugs recorded here are eligible for pruning on a later successful build.
const validSlug=slug=>/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug);
async function previousArticles(){try{const manifest=JSON.parse(await readFile(manifestFile,'utf8'));return Array.isArray(manifest.articles)?manifest.articles.filter(validSlug):[]}catch(error){if(error.code==='ENOENT')return [];throw error}}
async function pruneArticles(previous,current){for(const slug of previous){if(current.has(slug))continue;const directory=resolve(blogRoot,slug);if(!validSlug(slug)||!directory.startsWith(`${blogRoot}\\`) && !directory.startsWith(`${blogRoot}/`))throw Error(`Unsafe generated article path: ${slug}`);await rm(directory,{recursive:true,force:true})}}
const crumbs=(name,path)=>json({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:site},{'@type':'ListItem',position:2,name:'Knowledge Centre',item:site+'/blog/'},{'@type':'ListItem',position:3,name,item:site+path}]});
const categoryIcon='<svg class="kc-category-icon" viewBox="0 0 32 32" aria-hidden="true"><path d="M5 23 12 9l4 10 4-14 7 18M5 26h22"/></svg>';
const cta=`<div class="kc-actions"><a class="button" href="/samples/">Request Sample</a><a class="button-outline" href="/request-quote/">Request Quote</a></div>`;
const articleCta=`<div class="kc-actions"><p class="kc-actions__copy">Need help selecting the right yarn specification?</p><a class="button" href="/samples/">Request Sample</a><a class="button-outline" href="/request-quote/">Request Quote</a></div>`;
const {posts=[]}=await data(); const previous=await previousArticles(); const current=new Set(posts.map(post=>post.slug)); const allPosts=[...posts].sort((a,b)=>Date.parse(b.published_at||0)-Date.parse(a.published_at||0)); const homepageLatestPosts=allPosts.slice(0,5); const categoryPosts=new Map(categories.map(([slug])=>[slug,posts.filter(post=>canonicalCategory(post)?.[0]===slug)])); if(posts.some(post=>!validSlug(post.slug)))throw Error("Ghost returned an unsafe post slug."); for(const post of homepageLatestPosts){const category=canonicalCategory(post);if(category&&!categoryPosts.get(category[0]).includes(post))throw Error(`Homepage category validation failed for ${post.slug}.`)}
await emit('blog',page({title:'Zari & Metallic Yarn Knowledge Centre | Suvarnatantu',description:'Practical guidance on zari, metallic yarn, textile manufacturing and B2B sourcing from Suvarnatantu.',path:'/blog/',body:`<section class="kc-hero"><div class="kc-hero__media" aria-hidden="true"><img src="/assets/images/journey/metallic-zari-spools-2048.webp" alt="" width="2048" height="1668" fetchpriority="high" decoding="async"></div><div class="kc-hero__overlay" aria-hidden="true"></div><div class="wrap"><div class="kc-hero__content"><nav class="kc-hero__breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><span>Blog</span></nav><div class="eyebrow">Suvarnatantu Knowledge Centre</div><h1>Zari &amp; Metallic Yarn<br>Knowledge Centre</h1><p>Technical knowledge, manufacturing insights and sourcing guidance from the team at Suvarnatantu.</p>${cta}</div></div></section><section class="kc-section"><div class="wrap"><div class="kc-heading"><div><div class="eyebrow">Explore by topic</div></div></div><div class="kc-categories">${categories.map(([s,n,d,sub])=>`<a href="/blog/category/${s}/">${categoryIcon}<strong>${n}</strong><small>${sub}</small></a>`).join('')}</div></div></section><section class="kc-section kc-latest"><div class="wrap"><div class="kc-heading"><div><h2>Latest Articles</h2></div><a class="kc-all" href="/blog/articles/">View all articles →</a></div><div class="kc-grid">${homepageLatestPosts.map(card).join('')||'<p>No published articles are available yet.</p>'}</div></div></section><section class="kc-cta"><div class="wrap"><div><div class="eyebrow">Product development & supply</div><h2>Need help matching a yarn to your brief?</h2><p>Talk to the Suvarnatantu team about samples, specifications and B2B requirements.</p></div>${cta}</div></section>`}));
const articlesPath='/blog/articles/';
for(const post of posts)post.html=normalizeArticleHtml(post.html);
await emit('blog/articles',page({title:'All Articles | Suvarnatantu Knowledge Centre',description:'Explore the latest guides, technical knowledge, applications, manufacturing insights and sourcing resources from Suvarnatantu.',path:articlesPath,ld:crumbs('All Articles',articlesPath),body:`<section class="kc-category-hero"><div class="wrap"><nav class="kc-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><a href="/blog/">Knowledge Centre</a><span>/</span><span>All Articles</span></nav><div class="eyebrow">Knowledge Centre</div><h1>All Articles</h1><p>Explore the latest guides, technical knowledge, applications, manufacturing insights and sourcing resources from Suvarnatantu.</p></div></section><section class="kc-section kc-latest"><div class="wrap"><div class="kc-grid">${allPosts.map(card).join('')||'<p>No published articles are available yet.</p>'}</div></div></section>`}));
for(const p of posts){const related=posts.filter(x=>x.slug!==p.slug&&tag(x).slug===tag(p).slug).slice(0,3),path=`/blog/${p.slug}/`;const articleLd=json({'@context':'https://schema.org','@type':'Article',headline:p.title,description:desc(p),image:/^http/.test(img(p))?img(p):site+img(p),datePublished:p.published_at,dateModified:p.updated_at||p.published_at,mainEntityOfPage:site+path,author:{'@type':'Organization',name:p.primary_author?.name||'Suvarnatantu'},publisher:{'@type':'Organization',name:'Suvarnatantu'}});await emit(`blog/${p.slug}`,page({title:p.meta_title||`${p.title} | Suvarnatantu Knowledge Centre`,description:p.meta_description||desc(p),path,type:'article',image:p.og_image||img(p),ogTitle:p.og_title,ogDescription:p.og_description,ld:articleLd+crumbs(p.title,path),body:`<article class="kc-article"><div class="wrap"><nav class="kc-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><a href="/blog/">Knowledge Centre</a><span>/</span><span>${esc(p.title)}</span></nav><a class="kc-tag" href="/blog/category/${esc(tag(p).slug)}/">${esc(tag(p).name)}</a><h1>${esc(p.title)}</h1><p class="kc-dek">${esc(desc(p))}</p><div class="kc-meta">By ${esc(p.primary_author?.name||'Suvarnatantu Technical Team')} · <time datetime="${p.published_at}">${fmt(p.published_at)}</time> · ${p.reading_time||4} min read</div><img class="kc-article__image" src="${esc(img(p))}" alt="${esc(p.feature_image_alt||p.title)}" width="1600" height="900"><div class="kc-prose">${p.html||`<p>${esc(desc(p))}</p>`}</div>${articleCta}</div></article><section class="kc-section kc-related"><div class="wrap"><div class="eyebrow">Related articles</div><h2>Continue reading</h2><div class="kc-grid">${related.map(card).join('')||'<p>More articles will be added soon.</p>'}</div></div></section>`}))}
for(const [slug,name,copy] of categories){const path=`/blog/category/${slug}/`,subset=categoryPosts.get(slug);await emit(`blog/category/${slug}`,page({title:`${name} | Suvarnatantu Knowledge Centre`,description:copy,path,ld:crumbs(name,path),body:`<section class="kc-category-hero"><div class="wrap"><nav class="kc-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><a href="/blog/">Knowledge Centre</a><span>/</span><span>${name}</span></nav><div class="eyebrow">Knowledge Centre category</div><h1>${name}</h1><p>${copy}</p></div></section><section class="kc-section kc-latest"><div class="wrap"><div class="kc-grid">${subset.map(card).join('')||`<p>Articles for ${name} will appear here as they are published.</p>`}</div></div></section>`}))}
await pruneArticles(previous,current); await mkdir(blogRoot,{recursive:true}); await writeFile(manifestFile,`${JSON.stringify({version:1,articles:[...current].sort()},null,2)}\n`); console.log(`Generated ${posts.length} articles, ${categories.length} categories and the blog homepage.`); for(const [slug,name] of categories)console.log(`${name}: ${categoryPosts.get(slug).length}`);
