import {access,readFile} from 'node:fs/promises';
import {resolve} from 'node:path';

const root=resolve(import.meta.dirname,'..'),site='https://suvarnatantu.com';
const categories=['metallic-yarn','zari-yarn','technical-knowledge','applications','manufacturing','export-sourcing','industry-insights'];
const redirects=JSON.parse(await readFile(resolve(root,'firebase.json'),'utf8')).hosting.redirects.map(rule=>rule.regex);
const sitemap=await readFile(resolve(root,'sitemap.xml'),'utf8'),robots=await readFile(resolve(root,'robots.txt'),'utf8'),homepage=await readFile(resolve(root,'index.html'),'utf8');
const manifest=JSON.parse(await readFile(resolve(root,'blog','.ghost-generated.json'),'utf8'));
const topicPages=[
  ['zari-lab/tpm/index.html','https://suvarnatantu.com/zari-lab/tpm/'],['specifications/yarn-tpm-guide.html','https://suvarnatantu.com/specifications/yarn-tpm-guide/'],['blog/what-is-tpm-in-zari-yarn/index.html','https://suvarnatantu.com/blog/what-is-tpm-in-zari-yarn/'],
  ['zari-lab/denier/index.html','https://suvarnatantu.com/zari-lab/denier/'],['specifications/yarn-denier-guide.html','https://suvarnatantu.com/specifications/yarn-denier-guide/'],['blog/what-is-denier-in-metallic-yarn/index.html','https://suvarnatantu.com/blog/what-is-denier-in-metallic-yarn/']
];
const topicHtml=await Promise.all(topicPages.map(async([path,canonical])=>{const html=await readFile(resolve(root,path),'utf8');if(html.includes('noindex')||!html.includes(`rel="canonical" href="${canonical}"`))throw Error(`Invalid topic page: ${path}`);if((html.match(/<h1[ >]/g)||[]).length!==1)throw Error(`Invalid H1 count: ${path}`);return html;}));
for(const group of [topicHtml.slice(0,3),topicHtml.slice(3)]){const titles=group.map(html=>html.match(/<title>([^<]+)/)?.[1]),h1s=group.map(html=>html.match(/<h1[^>]*>([^<]+)/)?.[1]);if(new Set(titles).size!==3||new Set(h1s).size!==3)throw Error('TPM or Denier topic intents are not distinct.');}
const urls=[...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(([,url])=>url);
if(!sitemap.startsWith('<?xml')||!sitemap.includes('<urlset '))throw Error('Sitemap XML is invalid.');
if(!robots.includes('Sitemap: https://suvarnatantu.com/sitemap.xml'))throw Error('robots.txt is missing the sitemap declaration.');
if(new Set(urls).size!==urls.length)throw Error('Sitemap contains duplicate URLs.');
for(const url of urls)if(!url.startsWith(`${site}/`)||!url.endsWith('/'))throw Error(`Non-canonical sitemap URL: ${url}`);
for(const path of ['/','/blog/','/blog/articles/',...categories.map(slug=>`/blog/category/${slug}/`),...manifest.articles.map(slug=>`/blog/${slug}/`)])if(!urls.includes(site+path))throw Error(`Sitemap is missing ${path}`);
for(const url of urls)if(url.includes('enquiry-thank-you')||redirects.some(regex=>new RegExp(regex).test(new URL(url).pathname)))throw Error(`Sitemap contains a noindex or redirect-source URL: ${url}`);
for(const path of ['/industries/','/export/','/applications/','/zari-lab/','/manufacturing/'])if(!homepage.includes(`href="${path}"`))throw Error(`Homepage is missing ${path}`);
if(homepage.includes('nav-unavailable'))throw Error('Homepage retains obsolete unavailable navigation.');
const blogHome=await readFile(resolve(root,'blog','index.html'),'utf8'),archivePath=resolve(root,'blog','articles','index.html');
const archiveAvailable=await access(archivePath).then(()=>true,()=>false),archive=archiveAvailable?await readFile(archivePath,'utf8'):null;
for(const slug of manifest.articles){const html=await readFile(resolve(root,'blog',slug,'index.html'),'utf8');if((html.match(/<h1[ >]/g)||[]).length!==1)throw Error(`${slug} does not have exactly one H1.`);if(!html.includes(`rel="canonical" href="${site}/blog/${slug}/"`))throw Error(`${slug} is missing its canonical URL.`);const category=categories.find(value=>html.includes(`/blog/category/${value}/`));const categoryPage=await readFile(resolve(root,'blog','category',category,'index.html'),'utf8');for(const page of [blogHome,categoryPage,...(archive?[archive]:[])])if(!page.includes(`href="/blog/${slug}/"`))throw Error(`${slug} is orphaned from blog discovery pages.`);}
console.log(`Validated ${urls.length} sitemap URLs, ${manifest.articles.length} articles, and ${categories.length} blog categories.${archiveAvailable?' Archive links validated.':' Archive output is generated by the Ghost build and is not available locally.'}`);
